{{- if .Values.sonar.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: SonarGroup
metadata:
  name: sonar-developers
spec:
  sonarOwner: sonar
  name: sonar-developers
  description: "EDP Default Developers (DO NOT REMOVE)"
{{ end }}
