{{- if .Values.sonar.deploy -}}
apiVersion: v2.edp.epam.com/v1alpha1
kind: SonarPermissionTemplate
metadata:
  name: edp-default
spec:
  sonarOwner: sonar
  name: edp-default
  description: "EDP permission templates (DO NOT REMOVE)"
  projectKeyPattern: ".+"
  groupPermissions:
    - groupName: sonar-administrators
      permissions: [ "admin", "user" ]
    - groupName: sonar-developers
      permissions: [ "codeviewer", "issueadmin", "securityhotspotadmin", "user" ]
{{ end }}
