apiVersion: edp.epam.com/v1alpha1
kind: SonarPermissionTemplate
metadata:
  name: edp-default
spec:
  name: edp-default
  description: "EDP permission templates"
  projectKeyPattern: ".+"
  default: true
  groupsPermissions:
      sonar-users:
        - issueadmin
      sonar-developers:
        - scan
  sonarRef:
    name: sonar
