apiVersion: v2.edp.epam.com/v1alpha1
kind: SonarPermissionTemplate
metadata:
  name: test-tpl321
spec:
  sonarOwner: sonar
  name: test-tpl321
  description: "tpl desc"
  projectKeyPattern: ".+"
  groupPermissions:
    - groupName: testgroup1
      permissions: ["scan", "user"]


