apiVersion: v2.edp.epam.com/v1alpha1
kind: SonarPermissionTemplate
metadata:
  name: edp-default
spec:
  sonarOwner: sonar
  name: edp-default
  description: "EDP permission templates"
  projectKeyPattern: ".+"
  groupPermissions:
    - groupName: sonar-administrators
      permissions: [ "admin" ]
    - groupName: sonar-developers
      permissions: [ "codeviewer", "issueadmin", "securityhotspotadmin", "user" ]