apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sonargroups.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  names:
    kind: SonarGroup
    listKind: SonarGroupList
    plural: sonargroups
    singular: sonargroup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                sonarOwner:
                  type: string
                  description: 'name of root sonar custom resource'
                name:
                  type: string
                  description: 'group name'
                description:
                  type: string
              required:
                - sonarOwner
                - name
              type: object
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}