# permissions for end users to edit sonars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonar-operator
    app.kubernetes.io/part-of: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonar-editor-role
rules:
- apiGroups:
  - v2.edp.epam.com
  resources:
  - sonars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v2.edp.epam.com
  resources:
  - sonars/status
  verbs:
  - get
