# permissions for end users to view sonarqualitygates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonarqualitygate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonar-operator
    app.kubernetes.io/part-of: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonarqualitygate-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualitygates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualitygates/status
  verbs:
  - get
