# permissions for end users to view sonarqualityprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sonarqualityprofile-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonar-operator
    app.kubernetes.io/part-of: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonarqualityprofile-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualityprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonarqualityprofiles/status
  verbs:
  - get
