# permissions for end users to view sonarpermissiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: sonarpermissiontemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonar-operator
    app.kubernetes.io/part-of: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonarpermissiontemplate-viewer-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonarpermissiontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonarpermissiontemplates/status
  verbs:
  - get
