# permissions for end users to edit sonargroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: sonargroup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sonar-operator
    app.kubernetes.io/part-of: sonar-operator
    app.kubernetes.io/managed-by: kustomize
  name: sonargroup-editor-role
rules:
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edp.epam.com
  resources:
  - sonargroups/status
  verbs:
  - get
