## Append samples you want in your CSV to this file as resources ##
resources:
- edp_v1alpha1_sonar.yaml
- edp_v1alpha1_sonaruser.yaml
- edp_v1alpha1_sonarqualitygate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
