global:
  edpName: ""
  platform: "openshift"
  dnsWildCard: "delivery.aws.main.edp.projects.epam.com"
  openshift:
    deploymentType: "deploymentConfigs"

name: sonar-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  name: epamedp/sonar-operator
  # if not defined then .Chart.AppVersion is used
  version:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

sonar:
  deploy: true
  name: "sonar"
  image: "sonarqube"
  version: "7.9-community"
  imagePullPolicy: "IfNotPresent"
  initImage: "busybox"
  basePath: ""
  imagePullSecrets:
  storage:
    data:
      class: gp2
      size: 1Gi
    database:
      class: gp2
      size: 1Gi
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    annotations: {}

  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1.5Gi

  db:
    image: "postgres:9.6"
    imagePullPolicy: "IfNotPresent"
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 64Mi
    annotations: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
