apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sonar.name }}-install-plugins
  labels:
    app: {{ .Values.sonar.name }}
    {{- include "sonar-operator.labels" . | nindent 4 }}
data:
  install_plugins.sh: |-
    {{- if .Values.sonar.plugins.httpProxy }}
    export http_proxy={{ .Values.sonar.plugins.httpProxy }}
    {{- end }}
    {{- if .Values.sonar.plugins.httpsProxy }}
    export https_proxy={{ .Values.sonar.plugins.httpsProxy }}
    {{- end }}
    {{- if .Values.sonar.plugins.noProxy }}
    export no_proxy={{ .Values.sonar.plugins.noProxy }}
    {{- end }}
    {{- if .Values.sonar.plugins.install }}
      rm -f {{ .Values.sonar.sonarqubeFolder }}/extensions/downloads/*
      {{ range $index, $val := .Values.sonar.plugins.install }}
      echo {{ $val | quote }} >> {{ $.Values.sonar.sonarqubeFolder }}/extensions/downloads/list{{ end }}
      cat {{ .Values.sonar.sonarqubeFolder }}/extensions/downloads/list | xargs -n 1 -P 8 wget --directory-prefix {{ .Values.sonar.sonarqubeFolder }}/extensions/downloads --no-verbose{{ if .Values.sonar.plugins.noCheckCertificate }} --no-check-certificate{{ end }}
      rm {{ .Values.sonar.sonarqubeFolder }}/extensions/downloads/list
    {{- end }}
    {{- if .Values.sonar.plugins.lib }}
    {{- range $index, $val := .Values.sonar.plugins.lib }}
      cp -f {{ $.Values.sonar.sonarqubeFolder }}/extensions/downloads/{{ $val }} {{ $.Values.sonar.sonarqubeFolder }}/lib/common/{{ $val }}
    {{- end }}
    {{- end }}
