{{if or (eq .Values.global.platform "kubernetes") (eq .Values.global.openshift.deploymentType "deployments")}}
{{if .Values.sonar.deploy}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  labels:
    app: sonar
    {{- include "sonar-operator.labels" . | nindent 4 }}
  {{- with .Values.sonar.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonar
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonar
    spec:
      {{- if .Values.sonar.imagePullSecrets}}
      imagePullSecrets:
        {{- range .Values.sonar.imagePullSecrets }}
        - {{. -}}
        {{- end -}}
      {{end}}
      containers:
        - args:
            - -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
          env:
            - name: SONAR_WEB_JAVAOPTS
              value: {{ template "sonarqube.jvmOpts" . }}
            - name: SONAR_CE_JAVAOPTS
              value: {{ template "sonarqube.jvmCEOpts" . }}
            - name: SONARQUBE_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: sonar-db
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: sonar-db
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-db/sonar
            - name: sonar.web.context
              value: {{if .Values.sonar.basePath}}"/{{.Values.sonar.basePath}}"{{else}}/{{end}}
            {{- with .Values.sonar.env }}
            {{- . | toYaml | trim | nindent 12 }}
            {{- end }}
          image: "{{.Values.sonar.image}}:{{.Values.sonar.version}}"
          imagePullPolicy: "{{ .Values.sonar.imagePullPolicy }}"
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          name: sonar
          ports:
            - containerPort: 9000
              name: sonar
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.sonar.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: {{ .Values.sonar.sonarqubeFolder }}/extensions/plugins
              name: data
              subPath: extensions/plugins
            {{- if .Values.sonar.caCerts.enabled }}
            - mountPath: {{ .Values.sonar.sonarqubeFolder }}/certs
              name: data
              subPath: certs
            {{- end }}
      dnsPolicy: ClusterFirst
      initContainers:
      {{- if .Values.sonar.caCerts.enabled }}
        - name: ca-certs
          image: {{ default "adoptopenjdk/openjdk11:alpine" .Values.sonar.caCerts.image }}
          imagePullPolicy: {{ .Values.sonar.imagePullPolicy  }}
          command: ["sh"]
          args: ["-c", "cp -f \"${JAVA_HOME}/lib/security/cacerts\" /tmp/certs/cacerts; if [ \"$(ls /tmp/secrets/ca-certs)\" ]; then for f in /tmp/secrets/ca-certs/*; do keytool -importcert -file \"${f}\" -alias \"$(basename \"${f}\")\" -keystore /tmp/certs/cacerts -storepass changeit -trustcacerts -noprompt; done; fi;"]
          {{- if $securityContext := .Values.sonar.initContainers.securityContext }}
          securityContext:
{{ toYaml $securityContext | indent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp/certs
              name: data
              subPath: certs
            - mountPath: /tmp/secrets/ca-certs
              name: ca-certs
      {{- end }}
      {{- if .Values.sonar.plugins.install }}
        - name: install-plugins
          image: {{ default "epamedp/alpine-wget:1.0.3" .Values.sonar.plugins.image }}
          imagePullPolicy: {{ .Values.sonar.imagePullPolicy }}
          command: ["sh",
            "-e",
            "/tmp/scripts/install_plugins.sh"]
          volumeMounts:
            - mountPath: {{ .Values.sonar.sonarqubeFolder }}/extensions/plugins
              name: data
              subPath: extensions/plugins
            - name: install-plugins
              mountPath: /tmp/scripts/
            {{- if .Values.sonar.plugins.netrcCreds }}
            - name: plugins-netrc-file
              mountPath: /root
            {{- end }}
          {{- if $securityContext := .Values.sonar.initContainers.securityContext }}
          securityContext:
{{ toYaml $securityContext | indent 12 }}
          {{- end }}
          resources:
{{ toYaml (default .Values.sonar.initContainers.resources .Values.sonar.plugins.resource) | indent 12 }}
          {{- with .Values.env }}
            {{- . | toYaml | trim | nindent 12 }}
          {{- end }}
      {{- end }}
        - command:
            - sh
            - -c
            - while ! nc -w 1 sonar-db 5432 </dev/null; do echo waiting for sonar-db;
              sleep 10; done;
          image: {{.Values.sonar.initImage}}
          imagePullPolicy: "{{ .Values.sonar.imagePullPolicy }}"
          name: sonarinit
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      serviceAccount: sonar
      serviceAccountName: sonar
      terminationGracePeriodSeconds: 30
      volumes:
        - name: install-plugins
          configMap:
            name: {{ .Values.sonar.name }}-install-plugins
            items:
              - key: install_plugins.sh
                path: install_plugins.sh
        - name: data
          persistentVolumeClaim:
            claimName: sonar-data
        {{- if .Values.sonar.caCerts.enabled }}
        - name: ca-certs
          secret:
            secretName: {{ .Values.sonar.caCerts.secret }}
        {{- end }}
      {{- with .Values.sonar.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sonar.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sonar.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{end}}
{{end}}
